[project]
name = "gitchart"
version = "0.1.0"
description = "GitHub contribution chart API : generate SVG contribution graphs with custom colors and date ranges"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi>=0.136.1",
    "httpx>=0.28.1",
    "lxml>=6.1.0",
    "uvicorn>=0.46.0",
]
